Repository andostronaut/cocli, pull requests merged in 2024-10, with the labels that each got.

#49 feat: dont compile binary in script but install directly with global flag
  scripts/install.sh
Labels: automated, pull-request

#50 feat: specify comment for install in script
  scripts/install.sh
Labels: automated, pull-request, hacktoberfest-accepted

#52 fix: handle checking if error while installing
  scripts/install.sh
Labels: automated, pull-request, hacktoberfest-accepted

#53 docs: update readme doc to add global in install
  README.md
Labels: automated, pull-request, hacktoberfest-accepted

#54 typo: update readme
  README.md
Labels: hacktoberfest-accepted

#55 typo: use refactor instead of refact cf conventional commit
  README.md
  src/helpers/prompts.ts
Labels: hacktoberfest-accepted
